import type { Equipment, TripEquipment } from "@/types";
import { DEFAULT_EQUIPMENT_CATEGORY_IDS as CAT } from "@/lib/mock-data/equipment-categories";

export const equipment: Equipment[] = [
 {
 id: "eq-tent",
 ownerId: "profile-oksana",
 name: "Tent",
 categoryId: CAT.TENT,
 brand: "Big Agnes",
 model: "Copper Spur HV UL2",
 weightGrams: 1380,
 purchaseDate: "2022-04-12",
 purchasePrice: 449,
 notes: "Excellent for alpine bikepacking.",
 photoUrl:
 "https://images.unsplash.com/photo-1478131143081-80f7f84b47c7?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-sleeping-bag",
 ownerId: "profile-oksana",
 name: "Sleeping Bag",
 categoryId: CAT.SLEEPING_BAG,
 brand: "Western Mountaineering",
 model: "Ultralite",
 weightGrams: 850,
 purchaseDate: "2021-09-03",
 notes: "Comfort down to 0°C with liner.",
 photoUrl:
 "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-sleeping-pad",
 ownerId: "profile-oksana",
 name: "Sleeping Pad",
 categoryId: CAT.SLEEPING_PAD,
 brand: "Therm-a-Rest",
 model: "NeoAir XLite",
 weightGrams: 340,
 purchaseDate: "2022-04-12",
 isActive: true,
 },
 {
 id: "eq-backpack",
 ownerId: "profile-oksana",
 name: "Backpack",
 categoryId: CAT.BACKPACK,
 brand: "Osprey",
 model: "Exos 58",
 weightGrams: 1120,
 notes: "Primary multi-day hiking pack.",
 photoUrl:
 "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-bike",
 ownerId: "profile-oksana",
 name: "Bike",
 categoryId: CAT.BIKE,
 brand: "Cube",
 model: "Nuroad C:62",
 weightGrams: 9200,
 purchaseDate: "2023-03-18",
 purchasePrice: 2499,
 notes: "Gravel setup for bikepacking loops.",
 photoUrl:
 "https://images.unsplash.com/photo-1485965120188-e220f721d03e?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-helmet",
 ownerId: "profile-oksana",
 name: "Helmet",
 categoryId: CAT.HELMET,
 brand: "Giro",
 model: "Agilis MIPS",
 weightGrams: 260,
 isActive: true,
 },
 {
 id: "eq-stove",
 ownerId: "profile-oksana",
 name: "Stove",
 categoryId: CAT.STOVE,
 brand: "MSR",
 model: "PocketRocket 2",
 weightGrams: 73,
 isActive: true,
 },
 {
 id: "eq-jetboil",
 ownerId: "profile-oksana",
 name: "Jetboil Flash",
 categoryId: CAT.STOVE,
 brand: "Jetboil",
 model: "Flash",
 weightGrams: 371,
 notes: "Fast boils at altitude.",
 isActive: true,
 },
 {
 id: "eq-drone",
 ownerId: "profile-oksana",
 name: "Drone",
 categoryId: CAT.DRONE,
 brand: "DJI",
 model: "Mini 4 Pro",
 weightGrams: 249,
 purchaseDate: "2024-01-20",
 purchasePrice: 759,
 photoUrl:
 "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-action-camera",
 ownerId: "profile-oksana",
 name: "Action Camera",
 categoryId: CAT.ACTION_CAMERA,
 brand: "DJI",
 model: "Osmo Action 5 Pro",
 weightGrams: 146,
 purchaseDate: "2024-09-10",
 isActive: true,
 },
 {
 id: "eq-camera",
 ownerId: "profile-oksana",
 name: "Camera",
 categoryId: CAT.CAMERA,
 brand: "Sony",
 model: "A7C II",
 weightGrams: 514,
 notes: "Travel photography body.",
 photoUrl:
 "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
 isActive: true,
 },
 {
 id: "eq-shoes",
 ownerId: "profile-oksana",
 name: "Shoes",
 categoryId: CAT.SHOES,
 brand: "Salomon",
 model: "X Ultra 4 GTX",
 weightGrams: 720,
 isActive: true,
 },
 {
 id: "eq-jacket",
 ownerId: "profile-oksana",
 name: "Jacket",
 categoryId: CAT.JACKET,
 brand: "Arc'teryx",
 model: "Beta LT",
 weightGrams: 315,
 isActive: true,
 },
 {
 id: "eq-power-bank",
 ownerId: "profile-oksana",
 name: "Power Bank",
 categoryId: CAT.POWER_BANK,
 brand: "Anker",
 model: "737 PowerCore 24K",
 weightGrams: 622,
 isActive: true,
 },
 {
 id: "eq-water-filter",
 ownerId: "profile-oksana",
 name: "Water Filter",
 categoryId: CAT.WATER_FILTER,
 brand: "Sawyer",
 model: "Squeeze",
 weightGrams: 85,
 isActive: true,
 },
 {
 id: "eq-trekking-poles",
 ownerId: "profile-oksana",
 name: "Trekking Poles",
 categoryId: CAT.TREKKING_POLES,
 brand: "Black Diamond",
 model: "Distance Carbon Z",
 weightGrams: 350,
 isActive: true,
 },
 {
 id: "eq-gps",
 ownerId: "profile-oksana",
 name: "GPS Watch",
 categoryId: "ecat-custom-gps-watch",
 brand: "Garmin",
 model: "Fenix 7",
 weightGrams: 79,
 purchaseDate: "2023-11-05",
 purchasePrice: 699,
 isActive: true,
 },
 {
 id: "eq-first-aid",
 ownerId: "profile-oksana",
 name: "First Aid Kit",
 categoryId: CAT.FIRST_AID_KIT,
 brand: "Adventure Medical",
 model: "Ultralight .7",
 weightGrams: 99,
 isActive: true,
 },
 {
 id: "eq-old-tent",
 ownerId: "profile-oksana",
 name: "Tent",
 categoryId: CAT.TENT,
 brand: "MSR",
 model: "Hubba Hubba NX",
 weightGrams: 1540,
 notes: "Retired after Big Agnes upgrade.",
 isActive: false,
 },
];

export const tripEquipmentLinks: TripEquipment[] = [
 // Switzerland Bikepacking
 { id: "te-ch-1", tripId: "trip-ch", equipmentId: "eq-tent" },
 { id: "te-ch-2", tripId: "trip-ch", equipmentId: "eq-sleeping-bag" },
 { id: "te-ch-3", tripId: "trip-ch", equipmentId: "eq-sleeping-pad" },
 { id: "te-ch-4", tripId: "trip-ch", equipmentId: "eq-jetboil" },
 { id: "te-ch-5", tripId: "trip-ch", equipmentId: "eq-drone" },
 { id: "te-ch-6", tripId: "trip-ch", equipmentId: "eq-action-camera" },
 { id: "te-ch-7", tripId: "trip-ch", equipmentId: "eq-bike" },
 { id: "te-ch-8", tripId: "trip-ch", equipmentId: "eq-helmet" },
 { id: "te-ch-9", tripId: "trip-ch", equipmentId: "eq-gps" },
 { id: "te-ch-10", tripId: "trip-ch", equipmentId: "eq-trekking-poles" },
 { id: "te-ch-11", tripId: "trip-ch", equipmentId: "eq-power-bank" },
 // Portugal Active
 { id: "te-pt-1", tripId: "trip-pt", equipmentId: "eq-shoes" },
 { id: "te-pt-2", tripId: "trip-pt", equipmentId: "eq-jacket" },
 { id: "te-pt-3", tripId: "trip-pt", equipmentId: "eq-camera" },
 { id: "te-pt-4", tripId: "trip-pt", equipmentId: "eq-action-camera" },
 { id: "te-pt-5", tripId: "trip-pt", equipmentId: "eq-gps" },
 { id: "te-pt-6", tripId: "trip-pt", equipmentId: "eq-backpack" },
 // Carpathians Hiking
 { id: "te-ua-1", tripId: "trip-ua", equipmentId: "eq-tent" },
 { id: "te-ua-2", tripId: "trip-ua", equipmentId: "eq-sleeping-bag" },
 { id: "te-ua-3", tripId: "trip-ua", equipmentId: "eq-sleeping-pad" },
 { id: "te-ua-4", tripId: "trip-ua", equipmentId: "eq-backpack" },
 { id: "te-ua-5", tripId: "trip-ua", equipmentId: "eq-stove" },
 { id: "te-ua-6", tripId: "trip-ua", equipmentId: "eq-shoes" },
 { id: "te-ua-7", tripId: "trip-ua", equipmentId: "eq-trekking-poles" },
 { id: "te-ua-8", tripId: "trip-ua", equipmentId: "eq-water-filter" },
 { id: "te-ua-9", tripId: "trip-ua", equipmentId: "eq-first-aid" },
 { id: "te-ua-10", tripId: "trip-ua", equipmentId: "eq-gps" },
 // Faroe Islands (planning)
 { id: "te-fo-1", tripId: "trip-fo", equipmentId: "eq-jacket" },
 { id: "te-fo-2", tripId: "trip-fo", equipmentId: "eq-drone" },
 { id: "te-fo-3", tripId: "trip-fo", equipmentId: "eq-camera" },
 { id: "te-fo-4", tripId: "trip-fo", equipmentId: "eq-trekking-poles" },
];
