import type { Place } from "@/types";

export const places: Place[] = [
 {
 id: "place-ch-1",
 tripId: "trip-ch",
 name: "Julier Pass Summit",
 category: "VIEWPOINT",
 lat: 46.474,
 lng: 9.717,
 country: "Switzerland",
 region: "Graubünden",
 description: "2,284 m — first major col of the loop, wind and wide views.",
 photoIds: ["photo-ch-1"],
 },
 {
 id: "place-ch-2",
 tripId: "trip-ch",
 name: "Lago di Lei",
 category: "VIEWPOINT",
 lat: 46.496,
 lng: 9.398,
 country: "Switzerland",
 region: "Graubünden",
 description: "Turquoise reservoir between granite walls — prime drone location.",
 photoIds: ["photo-ch-3", "photo-ch-4"],
 },
 {
 id: "place-ch-3",
 tripId: "trip-ch",
 name: "Albula Pass",
 category: "TRAIL",
 lat: 46.587,
 lng: 9.838,
 country: "Switzerland",
 region: "Graubünden",
 description: "Historic pass road with tight switchbacks and RhB viaducts nearby.",
 photoIds: ["photo-ch-5"],
 },
 {
 id: "place-ch-4",
 tripId: "trip-ch",
 name: "Chamanna Jenatsch",
 category: "HOSTEL",
 lat: 46.559,
 lng: 9.947,
 country: "Switzerland",
 region: "Albula",
 description: "Mountain hut at 2,655 m — hot soup and early alpine starts.",
 photoIds: [],
 },
 {
 id: "place-pt-1",
 tripId: "trip-pt",
 name: "Miradouro da Senhora do Monte",
 category: "VIEWPOINT",
 lat: 38.719,
 lng: -9.133,
 country: "Portugal",
 region: "Lisbon",
 description: "Highest viewpoint in Lisbon — Alfama rooftops and the Tagus.",
 photoIds: ["photo-pt-1"],
 },
 {
 id: "place-pt-2",
 tripId: "trip-pt",
 name: "Cabo da Roca",
 category: "VIEWPOINT",
 lat: 38.78,
 lng: -9.498,
 country: "Portugal",
 region: "Sintra-Cascais",
 description: "Westernmost point of mainland Europe — cliffs and Atlantic spray.",
 photoIds: ["photo-pt-3"],
 },
 {
 id: "place-pt-3",
 tripId: "trip-pt",
 name: "Ponta da Piedade",
 category: "VIEWPOINT",
 lat: 37.078,
 lng: -8.669,
 country: "Portugal",
 region: "Algarve",
 description: "Golden limestone stacks and sea caves near Lagos.",
 photoIds: ["photo-pt-5"],
 },
 {
 id: "place-ua-1",
 tripId: "trip-ua",
 name: "Hoverla Summit",
 category: "TRAIL",
 lat: 48.123,
 lng: 24.505,
 country: "Ukraine",
 region: "Chornohora",
 description: "Highest peak in Ukraine at 2,061 m — cloud sea on good days.",
 photoIds: ["photo-ua-2"],
 },
 {
 id: "place-ua-2",
 tripId: "trip-ua",
 name: "Yaremche",
 category: "OTHER",
 lat: 48.359,
 lng: 24.447,
 country: "Ukraine",
 region: "Ivano-Frankivsk Oblast",
 description: "Gateway town — Probiy waterfall and the Prut river valley.",
 photoIds: ["photo-ua-1"],
 },
 {
 id: "place-fo-1",
 tripId: "trip-fo",
 name: "Múlafossur Waterfall",
 category: "VIEWPOINT",
 lat: 62.051,
 lng: -7.234,
 country: "Faroe Islands",
 region: "Vágar",
 description: "Waterfall dropping into the Atlantic beside Gásadalur village.",
 photoIds: ["photo-fo-1"],
 },
 {
 id: "place-fo-2",
 tripId: "trip-fo",
 name: "Sørvágsvatn / Lake Leitisvatn",
 category: "VIEWPOINT",
 lat: 62.044,
 lng: -7.191,
 country: "Faroe Islands",
 region: "Vágar",
 description: "Optical illusion lake — appears to float above the ocean.",
 photoIds: ["photo-fo-2"],
 },
 {
 id: "place-fo-3",
 tripId: "trip-fo",
 name: "Mykines",
 category: "OTHER",
 lat: 62.106,
 lng: -7.636,
 country: "Faroe Islands",
 region: "Mykines",
 description: "Puffin colony island — day trip target, weather dependent.",
 photoIds: ["photo-fo-3"],
 },
];
