import type { Trip } from "@/types";

export const trips: Trip[] = [
 {
 id: "trip-ch",
 slug: "switzerland-bikepacking",
 ownerId: "profile-oksana",
 title: "Alpine Passes by Bike",
 subtitle: "Ten days of gravel, cols, and cold lakes in Graubünden",
 description:
 "A self-supported bikepacking loop through southeastern Switzerland — Julier and Albula passes, overnight in mountain huts, and drone flights over turquoise reservoirs. 680 km, 12,400 m climbing.",
 coverImageUrl:
 "https://images.unsplash.com/photo-1530122037263-a5f1f91d3f99?w=1600&h=900&fit=crop",
 country: "Switzerland",
 region: "Graubünden · Engadin · Albula",
 startDate: "2024-08-05",
 endDate: "2024-08-14",
 status: "published",
 visibility: "public",
 tags: ["bikepacking", "alps", "gravel", "drone"],
 adventureType: "BIKEPACKING",
 stats: {
 dayCount: 5,
 eventCount: 18,
 photoCount: 14,
 placeCount: 8,
 distanceKm: 680,
 elevationGainM: 12400,
 },
 },
 {
 id: "trip-pt",
 slug: "portugal-active",
 ownerId: "profile-oksana",
 title: "Portugal in Motion",
 subtitle: "Surf coast, cliff trails, and Lisbon nights",
 description:
 "Active travel down the Atlantic edge — coastal hikes in Sintra-Cascais, bike days along the Algarve, pasteis in Belém, and long golden evenings in Alfama.",
 coverImageUrl:
 "https://images.unsplash.com/photo-1555881400-74d7aca93a7b?w=1600&h=900&fit=crop",
 country: "Portugal",
 region: "Lisbon · Sintra · Algarve",
 startDate: "2025-09-12",
 endDate: "2025-09-22",
 status: "published",
 visibility: "public",
 tags: ["hiking", "cycling", "coastal", "photography"],
 adventureType: "MIXED",
 stats: {
 dayCount: 4,
 eventCount: 16,
 photoCount: 12,
 placeCount: 7,
 distanceKm: 210,
 elevationGainM: 3200,
 },
 },
 {
 id: "trip-ua",
 slug: "carpathians-hiking",
 ownerId: "profile-oksana",
 title: "Carpathian Summits",
 subtitle: "Hoverla, ridgelines, and wooden churches in the mist",
 description:
 "A week in the Ukrainian Carpathians — ridge trails above the tree line, nights in village guesthouses, rain on tin roofs, and the quiet reward of high meadows.",
 coverImageUrl:
 "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&h=900&fit=crop",
 country: "Ukraine",
 region: "Ivano-Frankivsk Oblast · Chornohora",
 startDate: "2025-07-01",
 endDate: "2025-07-07",
 status: "published",
 visibility: "public",
 tags: ["hiking", "mountains", "ukraine", "camping"],
 adventureType: "HIKING",
 stats: {
 dayCount: 3,
 eventCount: 12,
 photoCount: 9,
 placeCount: 5,
 distanceKm: 78,
 elevationGainM: 4100,
 },
 },
 {
 id: "trip-baltic",
 slug: "baltic-coast-active",
 ownerId: "profile-oksana",
 title: "Baltic Coast by Bike",
 subtitle: "Wind, dunes, and amber towns from Gdańsk to Klaipėda",
 description:
 "Currently on the road — coastal bike route through Pomerania and the Curonian Spit. Camping near dunes, ferry to Nida, and evening rides along the lagoon.",
 coverImageUrl:
 "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&h=900&fit=crop",
 country: "Poland · Lithuania",
 region: "Pomerania · Curonian Spit",
 startDate: "2026-06-28",
 endDate: "2026-07-12",
 status: "published",
 visibility: "private",
 tags: ["cycling", "coastal", "camping", "active"],
 adventureType: "CYCLING",
 stats: {
 dayCount: 2,
 eventCount: 9,
 photoCount: 6,
 placeCount: 4,
 distanceKm: 145,
 elevationGainM: 890,
 },
 },
 {
 id: "trip-fo",
 slug: "faroe-islands",
 ownerId: "profile-oksana",
 title: "Faroe Islands — Draft Route",
 subtitle: "Cliff paths, puffins, and North Atlantic light (planning)",
 description:
 "Wishlist trip for June 2026. Researching hut-to-hut hikes on Vágar and Streymoy, ferry hops to Mykines, and weather windows for drone flights over sea stacks.",
 coverImageUrl:
 "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1600&h=900&fit=crop",
 country: "Faroe Islands",
 region: "Streymoy · Vágar · Mykines",
 startDate: "2026-06-08",
 endDate: "2026-06-17",
 status: "planning",
 visibility: "unlisted",
 tags: ["wishlist", "hiking", "drone", "planning"],
 adventureType: "HIKING",
 stats: {
 dayCount: 2,
 eventCount: 7,
 photoCount: 3,
 placeCount: 4,
 },
 },
];
