import type { TripEvent } from "@/types";

export const carpathiansHikingEvents: TripEvent[] = [
 {
 id: "event-ua-1-1",
 tripId: "trip-ua",
 dayId: "day-ua-1",
 type: "TRANSPORT",
 title: "Night train Kyiv → Ivano-Frankivsk",
 startTime: "22:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 amount: 38,
 currency: "UAH",
 },
 {
 id: "event-ua-1-2",
 tripId: "trip-ua",
 dayId: "day-ua-1",
 type: "PHOTO_VIDEO",
 title: "Prut river valley at dawn",
 startTime: "08:30",
 placeId: "place-ua-2",
 photoIds: ["photo-ua-1"],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 2,
 },
 {
 id: "event-ua-1-3",
 tripId: "trip-ua",
 dayId: "day-ua-1",
 type: "SLEEP",
 title: "Village guesthouse in Yaremche",
 startTime: "21:00",
 placeId: "place-ua-2",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 amount: 650,
 currency: "UAH",
 },
 {
 id: "event-ua-2-1",
 tripId: "trip-ua",
 dayId: "day-ua-2",
 type: "HIKE",
 title: "Hoverla summit trail",
 description: "Six hours up through forest and scree. Clouds at the top.",
 startTime: "06:00",
 endTime: "14:30",
 placeId: "place-ua-1",
 photoIds: ["photo-ua-2"],
 cloudLinkIds: [],
 participantIds: ["profile-oksana"],
 tags: ["summit"],
 order: 1,
 distanceKm: 14,
 elevationGainM: 1450,
 },
 {
 id: "event-ua-2-2",
 tripId: "trip-ua",
 dayId: "day-ua-2",
 type: "FOOD",
 title: "Hut soup at the base",
 startTime: "15:30",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 2,
 amount: 120,
 currency: "UAH",
 },
 {
 id: "event-ua-2-3",
 tripId: "trip-ua",
 dayId: "day-ua-2",
 type: "NOTE",
 title: "Summit journal",
 description: "Couldn't see the valleys but the silence was worth it.",
 startTime: "13:15",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 },
 {
 id: "event-ua-3-1",
 tripId: "trip-ua",
 dayId: "day-ua-3",
 type: "HIKE",
 title: "Petros ridge traverse",
 startTime: "07:30",
 endTime: "16:00",
 photoIds: ["photo-ua-3"],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 18,
 elevationGainM: 920,
 },
 {
 id: "event-ua-3-2",
 tripId: "trip-ua",
 dayId: "day-ua-3",
 type: "TIP",
 title: "Carpathian weather tip",
 description: "Start before 7am in July — thunderstorms build by afternoon.",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 2,
 },
 {
 id: "event-ua-3-3",
 tripId: "trip-ua",
 dayId: "day-ua-3",
 type: "TRANSPORT",
 title: "Marshrutka back to Yaremche",
 startTime: "17:30",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 distanceKm: 38,
 },
];
