import type { TripEvent } from "@/types";

export const faroeIslandsEvents: TripEvent[] = [
 {
 id: "event-fo-1-1",
 tripId: "trip-fo",
 dayId: "day-fo-1",
 type: "NOTE",
 title: "Route draft v2",
 description: "Land Vágar 14:30, taxi to Gásadalur, shoot Múlafossur at 21:00 in June light.",
 photoIds: [],
 cloudLinkIds: ["cloud-fo-1"],
 participantIds: [],
 tags: ["planning"],
 order: 1,
 },
 {
 id: "event-fo-1-2",
 tripId: "trip-fo",
 dayId: "day-fo-1",
 type: "PLACE_VISIT",
 title: "Múlafossur — target shoot",
 description: "Wishlist: long exposure at dusk if wind < 10 m/s.",
 placeId: "place-fo-1",
 photoIds: ["photo-fo-1"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["wishlist"],
 order: 2,
 },
 {
 id: "event-fo-1-3",
 tripId: "trip-fo",
 dayId: "day-fo-1",
 type: "TIP",
 title: "Faroe ferry booking",
 description: "Book Mykines ferry 2–3 weeks ahead in summer. Have a backup day for wind.",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 },
 {
 id: "event-fo-1-4",
 tripId: "trip-fo",
 dayId: "day-fo-1",
 type: "PLACE_VISIT",
 title: "Sørvágsvatn optical illusion hike",
 placeId: "place-fo-2",
 photoIds: ["photo-fo-2"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["wishlist", "hike"],
 order: 4,
 },
 {
 id: "event-fo-2-1",
 tripId: "trip-fo",
 dayId: "day-fo-2",
 type: "NOTE",
 title: "Mykines weather window",
 description: "Check yr.no morning of — cancellation common above 15 m/s gusts.",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["planning"],
 order: 1,
 },
 {
 id: "event-fo-2-2",
 tripId: "trip-fo",
 dayId: "day-fo-2",
 type: "PLACE_VISIT",
 title: "Mykines puffin colony",
 placeId: "place-fo-3",
 photoIds: ["photo-fo-3"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["wishlist", "wildlife"],
 order: 2,
 },
 {
 id: "event-fo-2-3",
 tripId: "trip-fo",
 dayId: "day-fo-2",
 type: "PHOTO_VIDEO",
 title: "Sea stack flights — pending permits",
 description: "Researching local drone rules. May need guide for cliff launches.",
 photoIds: [],
 cloudLinkIds: ["cloud-fo-1"],
 participantIds: [],
 tags: ["planning", "drone"],
 order: 3,
 },
];
