import type { TripEvent } from "@/types";

export const portugalActiveEvents: TripEvent[] = [
 {
 id: "event-pt-1-1",
 tripId: "trip-pt",
 dayId: "day-pt-1",
 type: "TRANSPORT",
 title: "Taxi from Lisbon airport",
 description: "Morning arrival, ride to Alfama guesthouse.",
 startTime: "09:45",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 12,
 },
 {
 id: "event-pt-1-2",
 tripId: "trip-pt",
 dayId: "day-pt-1",
 type: "FOOD",
 title: "Pastéis de Belém",
 startTime: "14:00",
 photoIds: ["photo-pt-2"],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 2,
 amount: 12,
 currency: "EUR",
 },
 {
 id: "event-pt-1-3",
 tripId: "trip-pt",
 dayId: "day-pt-1",
 type: "PHOTO_VIDEO",
 title: "Golden hour over Alfama",
 startTime: "19:30",
 placeId: "place-pt-1",
 photoIds: ["photo-pt-1"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["sunset"],
 order: 3,
 },
 {
 id: "event-pt-1-4",
 tripId: "trip-pt",
 dayId: "day-pt-1",
 type: "SLEEP",
 title: "Guesthouse in Alfama",
 startTime: "22:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 4,
 amount: 85,
 currency: "EUR",
 },
 {
 id: "event-pt-2-1",
 tripId: "trip-pt",
 dayId: "day-pt-2",
 type: "HIKE",
 title: "Sintra palaces loop",
 description: "Mist, wet stone, Pena glimpses through cloud.",
 startTime: "09:00",
 endTime: "14:00",
 photoIds: ["photo-pt-4"],
 cloudLinkIds: [],
 participantIds: ["profile-oksana"],
 tags: ["trail"],
 order: 1,
 distanceKm: 11,
 elevationGainM: 480,
 },
 {
 id: "event-pt-2-2",
 tripId: "trip-pt",
 dayId: "day-pt-2",
 type: "PLACE_VISIT",
 title: "Cabo da Roca",
 description: "Wind so loud you can't hear the phone.",
 startTime: "16:00",
 placeId: "place-pt-2",
 photoIds: ["photo-pt-3"],
 cloudLinkIds: ["cloud-pt-2"],
 participantIds: [],
 tags: [],
 order: 2,
 },
 {
 id: "event-pt-2-3",
 tripId: "trip-pt",
 dayId: "day-pt-2",
 type: "NOTE",
 title: "Evening note",
 description: "Sintra is better on a weekday — fewer buses on the narrow roads.",
 startTime: "21:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["journal"],
 order: 3,
 },
 {
 id: "event-pt-3-1",
 tripId: "trip-pt",
 dayId: "day-pt-3",
 type: "BIKE",
 title: "Lagos coastal ride",
 startTime: "08:30",
 endTime: "12:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 34,
 elevationGainM: 380,
 },
 {
 id: "event-pt-3-2",
 tripId: "trip-pt",
 dayId: "day-pt-3",
 type: "PHOTO_VIDEO",
 title: "Ponta da Piedade stacks",
 startTime: "17:00",
 endTime: "18:30",
 placeId: "place-pt-3",
 photoIds: ["photo-pt-5"],
 cloudLinkIds: ["cloud-pt-1"],
 participantIds: [],
 tags: ["coastal"],
 order: 2,
 },
 {
 id: "event-pt-3-0",
 tripId: "trip-pt",
 dayId: "day-pt-3",
 type: "TRANSPORT",
 title: "Drive to Lagos",
 description: "Rental car from Sintra down to the Algarve coast.",
 startTime: "06:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 0,
 distanceKm: 286,
 },
 {
 id: "event-pt-3-3",
 tripId: "trip-pt",
 dayId: "day-pt-3",
 type: "FOOD",
 title: "Grilled sardines in Lagos",
 startTime: "20:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 amount: 24,
 currency: "EUR",
 },
 {
 id: "event-pt-4-1",
 tripId: "trip-pt",
 dayId: "day-pt-4",
 type: "HIKE",
 title: "Tagus riverfront walk",
 startTime: "10:00",
 endTime: "12:30",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 8,
 elevationGainM: 20,
 },
 {
 id: "event-pt-4-2",
 tripId: "trip-pt",
 dayId: "day-pt-4",
 type: "TRANSPORT",
 title: "Train to airport",
 startTime: "15:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 2,
 },
];
