import type { TripEvent } from "@/types";

export const switzerlandBikepackingEvents: TripEvent[] = [
 {
 id: "event-ch-1-1",
 tripId: "trip-ch",
 dayId: "day-ch-1",
 type: "NOTE",
 title: "Pre-ride checklist",
 description: "Tires at 2.1 bar, 12L water capacity, hut booking confirmed for day 4.",
 startTime: "06:30",
 photoIds: ["photo-ch-2"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["prep"],
 order: 1,
 },
 {
 id: "event-ch-1-0",
 tripId: "trip-ch",
 dayId: "day-ch-1",
 type: "TRANSPORT",
 title: "Shuttle to St. Moritz trailhead",
 description: "Van transfer with bikes from Thusis.",
 startTime: "05:45",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 0,
 distanceKm: 24,
 },
 {
 id: "event-ch-1-2",
 tripId: "trip-ch",
 dayId: "day-ch-1",
 type: "BIKE",
 title: "St. Moritz → Julier Pass",
 description: "Gravel climb on smooth forest roads, then exposed summit section.",
 startTime: "07:15",
 endTime: "11:30",
 placeId: "place-ch-1",
 photoIds: ["photo-ch-1"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["gravel", "pass"],
 order: 2,
 distanceKm: 42,
 elevationGainM: 980,
 },
 {
 id: "event-ch-1-3",
 tripId: "trip-ch",
 dayId: "day-ch-1",
 type: "FOOD",
 title: "Rosti at Silvaplana",
 startTime: "13:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 amount: 18,
 currency: "CHF",
 },
 {
 id: "event-ch-1-4",
 tripId: "trip-ch",
 dayId: "day-ch-1",
 type: "SLEEP",
 title: "Camping Val Bregaglia",
 description: "Small site by the river — heard cowbells all night.",
 startTime: "20:00",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["camp"],
 order: 4,
 amount: 22,
 currency: "CHF",
 },
 {
 id: "event-ch-2-1",
 tripId: "trip-ch",
 dayId: "day-ch-2",
 type: "BIKE",
 title: "Val Bregaglia traverse",
 startTime: "08:00",
 endTime: "16:30",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 86,
 elevationGainM: 1400,
 },
 {
 id: "event-ch-2-2",
 tripId: "trip-ch",
 dayId: "day-ch-2",
 type: "PHOTO_VIDEO",
 title: "Granite wall reflection pool",
 description: "Unmarked pull-off — worth the 10 min walk from the road.",
 startTime: "14:20",
 location: { latitude: 46.318, longitude: 9.612 },
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["landscape"],
 order: 2,
 },
 {
 id: "event-ch-3-1",
 tripId: "trip-ch",
 dayId: "day-ch-3",
 type: "BIKE",
 title: "Climb to Lago di Lei dam",
 startTime: "09:00",
 endTime: "11:00",
 placeId: "place-ch-2",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 28,
 elevationGainM: 720,
 },
 {
 id: "event-ch-3-2",
 tripId: "trip-ch",
 dayId: "day-ch-3",
 type: "PHOTO_VIDEO",
 title: "Reservoir orbit flight",
 description: "Two batteries, calm wind until 18:00. Best footage facing west.",
 startTime: "16:30",
 endTime: "18:45",
 location: {
 name: "Lago di Lei",
 latitude: 46.496,
 longitude: 9.398,
 },
 photoIds: ["photo-ch-3"],
 cloudLinkIds: ["cloud-ch-1"],
 participantIds: ["profile-oksana"],
 tags: ["4k", "d-log"],
 order: 2,
 },
 {
 id: "event-ch-3-3",
 tripId: "trip-ch",
 dayId: "day-ch-3",
 type: "PHOTO_VIDEO",
 title: "Golden hour at the dam wall",
 startTime: "19:00",
 location: {
 name: "Lago di Lei",
 latitude: 46.496,
 longitude: 9.398,
 },
 photoIds: ["photo-ch-4"],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["sunset"],
 order: 3,
 },
 {
 id: "event-ch-4-1",
 tripId: "trip-ch",
 dayId: "day-ch-4",
 type: "BIKE",
 title: "Albula Pass climb",
 startTime: "07:30",
 endTime: "12:00",
 placeId: "place-ch-3",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 54,
 elevationGainM: 1680,
 },
 {
 id: "event-ch-4-2",
 tripId: "trip-ch",
 dayId: "day-ch-4",
 type: "PHOTO_VIDEO",
 title: "Switchback top-down sequence",
 startTime: "11:15",
 location: {
 name: "Albula Pass",
 latitude: 46.587,
 longitude: 9.838,
 },
 photoIds: ["photo-ch-5"],
 cloudLinkIds: ["cloud-ch-2"],
 participantIds: [],
 tags: [],
 order: 2,
 },
 {
 id: "event-ch-4-3",
 tripId: "trip-ch",
 dayId: "day-ch-4",
 type: "SLEEP",
 title: "Chamanna Jenatsch",
 description: "Shared dorm, dinner included. Booked via SAC.",
 startTime: "19:30",
 placeId: "place-ch-4",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: ["hut"],
 order: 3,
 amount: 68,
 currency: "CHF",
 },
 {
 id: "event-ch-5-1",
 tripId: "trip-ch",
 dayId: "day-ch-5",
 type: "BIKE",
 title: "Engadin fast roll to St. Moritz",
 startTime: "08:00",
 endTime: "13:30",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 1,
 distanceKm: 62,
 elevationGainM: 420,
 },
 {
 id: "event-ch-5-2",
 tripId: "trip-ch",
 dayId: "day-ch-5",
 type: "EXPENSE",
 title: "Adventure totals logged",
 description: "Food, huts, camping, one broken spoke repair.",
 photoIds: [],
 cloudLinkIds: ["cloud-ch-3"],
 participantIds: [],
 tags: ["summary"],
 order: 2,
 amount: 890,
 currency: "CHF",
 },
 {
 id: "event-ch-5-3",
 tripId: "trip-ch",
 dayId: "day-ch-5",
 type: "TIP",
 title: "Swiss bikepacking tip",
 description: "Fill water at every fountain — August cols are dry above 2,000 m.",
 photoIds: [],
 cloudLinkIds: [],
 participantIds: [],
 tags: [],
 order: 3,
 },
];
