import type { DesignConcept } from "./types";

/** Ten visual directions for Memora — compare before picking one for implementation. */
export const designConcepts: DesignConcept[] = [
  {
    id: "scandinavian-light",
    name: "Clean Scandinavian",
    mode: "light",
    personality: "Calm, airy, understated travel journal with warm neutrals.",
    colors: {
      primary: "#1F7A8C",
      secondary: "#D98C5F",
      accent: "#E4572E",
      background: "#F7F5F2",
      surface: "#FFFFFF",
      surfaceMuted: "#F1EFEB",
      foreground: "#1C1917",
      mutedForeground: "#78716C",
      border: "#D7D0C6",
    },
    typography: {
      heading: "Inter",
      body: "Source Sans 3",
      h1: "32px / 1.15",
      h2: "24px / 1.2",
      h3: "20px / 1.25",
      bodySize: "16px / 1.6",
      labelSize: "13px / 1.4",
    },
    radius: { sm: "8px", md: "10px", lg: "12px", pill: "999px" },
    shadows: {
      sm: "0 1px 2px rgba(15, 23, 42, 0.06)",
      md: "0 8px 24px rgba(15, 23, 42, 0.08)",
      lg: "0 16px 40px rgba(15, 23, 42, 0.1)",
    },
    buttons: {
      primary: "Solid teal, white text, 10px radius, soft hover darken",
      secondary: "Outline teal on white, 1px border",
      ghost: "Transparent, hover surface-muted fill",
    },
    forms: "Filled light inputs (#F3F0EC), 1px warm border, 2px primary focus ring",
    cards: "White, 12px radius, shadow-sm, 20–24px padding, subtle dividers",
    tables: "Borderless, zebra rows on surface-muted, row hover #ECE7DF",
    navigation: "White header with thin border; off-white sidebar, active left strip",
    icons: "Lucide 1.5 stroke, slate default, primary on active/CTA only",
    status: {
      success: "#3C9D7A",
      warning: "#D98C5F",
      error: "#D95A4E",
      info: "#1F7A8C",
    },
    charts: "Thin line/area, 1–2 series, no gradients, muted grid",
    spacing: [4, 8, 12, 16, 24, 32, 48],
    motion: {
      duration: "150–180ms",
      easing: "ease-out",
      style: "Fade + translate-y-1 on enter",
    },
  },
  {
    id: "apple-minimal-light",
    name: "Apple-like Minimal",
    mode: "light",
    personality: "Monochrome clarity, micro-typography, system-like polish.",
    colors: {
      primary: "#0071E3",
      secondary: "#6E6E73",
      accent: "#FF9F0A",
      background: "#F5F5F7",
      surface: "#FFFFFF",
      surfaceMuted: "#E5E5EA",
      foreground: "#1D1D1F",
      mutedForeground: "#86868B",
      border: "#D2D2D7",
    },
    typography: {
      heading: "SF Pro Display / Inter",
      body: "SF Pro Text / Inter",
      h1: "34px / 1.1",
      h2: "24px / 1.15",
      h3: "19px / 1.2",
      bodySize: "15px / 1.5",
      labelSize: "12px / 1.35",
    },
    radius: { sm: "6px", md: "8px", lg: "14px", pill: "999px" },
    shadows: {
      sm: "none (border only)",
      md: "0 2px 8px rgba(0, 0, 0, 0.04)",
      lg: "0 8px 24px rgba(0, 0, 0, 0.08)",
    },
    buttons: {
      primary: "Pill, solid blue, white text",
      secondary: "Light grey fill #E5E5EA, no border",
      ghost: "Text-only with subtle hover grey",
    },
    forms: "White fields, 1px border, crisp blue focus, minimal helper text",
    cards: "Flat white, strong grid alignment, optional subtle top gradient",
    tables: "Edge-to-edge in card, light row separators, sticky header",
    navigation: "Translucent top bar (backdrop-blur), icon-first compact sidebar",
    icons: "Simple line, minimal color, consistent 1.5 stroke",
    status: {
      success: "#34C759",
      warning: "#FFCC00",
      error: "#FF3B30",
      info: "#0A84FF",
    },
    charts: "Thin lines, dots only, no area fills",
    spacing: [4, 8, 16, 24, 32, 40],
    motion: {
      duration: "200ms",
      easing: "ease-out",
      style: "Opacity + slight scale, no bounce",
    },
  },
  {
    id: "glass-light",
    name: "Modern Glassmorphism",
    mode: "light",
    personality: "Frosted panels over soft gradient — premium but restrained.",
    colors: {
      primary: "#2563EB",
      secondary: "#8B5CF6",
      accent: "#F97316",
      background: "linear-gradient(#F5FAFF, #F0F4FF, #F8F2FF)",
      surface: "rgba(255, 255, 255, 0.72)",
      surfaceMuted: "rgba(255, 255, 255, 0.55)",
      foreground: "#0F172A",
      mutedForeground: "#64748B",
      border: "rgba(255, 255, 255, 0.6)",
    },
    typography: {
      heading: "Sora",
      body: "Inter",
      h1: "32px / 1.15",
      h2: "24px / 1.2",
      h3: "20px / 1.25",
      bodySize: "16px / 1.55",
      labelSize: "13px / 1.4",
    },
    radius: { sm: "12px", md: "16px", lg: "20px", pill: "999px" },
    shadows: {
      sm: "0 4px 16px rgba(15, 23, 42, 0.08)",
      md: "0 18px 45px rgba(15, 23, 42, 0.14)",
      lg: "0 24px 60px rgba(15, 23, 42, 0.18)",
    },
    buttons: {
      primary: "Solid blue with subtle gradient + soft glow shadow",
      secondary: "Glass outline, backdrop-blur, white inner border",
      ghost: "Transparent glass hover",
    },
    forms: "Frosted inputs, semi-transparent bg, bright focus glow",
    cards: "Glass layers; dense content on opaque inner surface for contrast",
    tables: "On opaque surface, row borders with backdrop-blur header",
    navigation: "Floating rounded glass top nav + glass sidebar",
    icons: "Duotone where helpful, gradient accents sparingly",
    status: {
      success: "#22C55E",
      warning: "#EAB308",
      error: "#EF4444",
      info: "#2563EB",
    },
    charts: "Translucent area fills, glow on hover points",
    spacing: [4, 8, 12, 20, 28, 36],
    motion: {
      duration: "180–220ms",
      easing: "cubic-bezier(0.16, 0.84, 0.44, 1)",
      style: "Blur fade, glass melt transitions",
    },
  },
  {
    id: "premium-banking-light",
    name: "Premium Banking",
    mode: "light",
    personality: "Trust, stability, wealth-management gravitas.",
    colors: {
      primary: "#0F172A",
      secondary: "#1E293B",
      accent: "#C28C3C",
      background: "#F3F4F6",
      surface: "#FFFFFF",
      surfaceMuted: "#F9FAFB",
      foreground: "#0F172A",
      mutedForeground: "#64748B",
      border: "#E2E8F0",
    },
    typography: {
      heading: "Inter / Neue Haas Grotesk",
      body: "Source Sans 3",
      h1: "30px / 1.2",
      h2: "22px / 1.25",
      h3: "18px / 1.3",
      bodySize: "15px / 1.55",
      labelSize: "12px / 1.4 uppercase tracking-wide",
    },
    radius: { sm: "4px", md: "6px", lg: "8px", pill: "999px" },
    shadows: {
      sm: "0 1px 3px rgba(15, 23, 42, 0.08)",
      md: "0 10px 30px rgba(15, 23, 42, 0.12)",
      lg: "0 20px 50px rgba(15, 23, 42, 0.16)",
    },
    buttons: {
      primary: "Solid navy, white text, gold border on hover",
      secondary: "Outline navy, conservative radius",
      ghost: "Text navy, underline on hover for links",
    },
    forms: "White fields, navy labels, inline validation, clear hierarchy",
    cards: "KPI cards on navy with gold type; data cards on white",
    tables: "Strong borders, sticky headers, alternating rows",
    navigation: "Navy sidebar, white header, gold active indicator",
    icons: "Line icons navy; filled for primary nav only",
    status: {
      success: "#16A34A",
      warning: "#EAB308",
      error: "#DC2626",
      info: "#0EA5E9",
    },
    charts: "Bar + line, navy/gold/teal series, no decorative gradients",
    spacing: [4, 8, 16, 24, 32, 40],
    motion: {
      duration: "160ms",
      easing: "ease-out",
      style: "Minimal slide/fade, no flashy motion",
    },
  },
  {
    id: "soft-saas-light",
    name: "Soft Neutral SaaS",
    mode: "light",
    personality: "Friendly B2B SaaS — warm greys, rounded, approachable.",
    colors: {
      primary: "#6366F1",
      secondary: "#EC4899",
      accent: "#14B8A6",
      background: "#FAFAFA",
      surface: "#FFFFFF",
      surfaceMuted: "#F4F4F5",
      foreground: "#18181B",
      mutedForeground: "#71717A",
      border: "#E4E4E7",
    },
    typography: {
      heading: "Inter",
      body: "Inter",
      h1: "30px / 1.2",
      h2: "22px / 1.25",
      h3: "18px / 1.3",
      bodySize: "15px / 1.55",
      labelSize: "13px / 1.4",
    },
    radius: { sm: "8px", md: "12px", lg: "16px", pill: "999px" },
    shadows: {
      sm: "0 2px 8px rgba(15, 23, 42, 0.06)",
      md: "0 4px 12px rgba(15, 23, 42, 0.08)",
      lg: "0 12px 32px rgba(15, 23, 42, 0.1)",
    },
    buttons: {
      primary: "Solid indigo, medium weight label",
      secondary: "Soft grey bg, no border",
      ghost: "Hover surface-muted",
    },
    forms: "h-11 inputs, helper text below, soft inner shadow on focus",
    cards: "Soft panels, icon in circular tinted background",
    tables: "Status chips, row actions on hover",
    navigation: "Light sidebar, active pill highlight; header breadcrumbs only",
    icons: "2-tone icons in circular backgrounds",
    status: {
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#6366F1",
    },
    charts: "Soft curves, rounded tooltips",
    spacing: [8, 16, 24, 32, 40],
    motion: {
      duration: "180ms",
      easing: "ease-out",
      style: "Card hover scale 0.98→1, background fades",
    },
  },
  {
    id: "github-dark",
    name: "GitHub-inspired Dark",
    mode: "dark",
    personality: "Developer-friendly high-contrast dark, neutral and dense.",
    colors: {
      primary: "#2F81F7",
      secondary: "#6E7681",
      accent: "#3FB950",
      background: "#010409",
      surface: "#0D1117",
      surfaceMuted: "#161B22",
      foreground: "#E6EDF3",
      mutedForeground: "#8B949E",
      border: "#30363D",
    },
    typography: {
      heading: "Inter",
      body: "Inter",
      h1: "28px / 1.2",
      h2: "20px / 1.25",
      h3: "16px / 1.3",
      bodySize: "14px / 1.5",
      labelSize: "12px / 1.4",
    },
    radius: { sm: "4px", md: "6px", lg: "8px", pill: "999px" },
    shadows: {
      sm: "none (border emphasis)",
      md: "0 4px 12px rgba(0, 0, 0, 0.4)",
      lg: "0 8px 24px rgba(0, 0, 0, 0.5)",
    },
    buttons: {
      primary: "Blue bg, white text, #1F6FEB border",
      secondary: "Dark grey bg, light border",
      ghost: "Transparent, hover surface-muted",
    },
    forms: "Dark fields, light border, blue focus ring",
    cards: "surface-alt + border #30363D, compact density",
    tables: "Dense, horizontal separators, row hover #161B22",
    navigation: "Dark top nav, optional sidebar for dashboard",
    icons: "Monochrome line, primary tint on active",
    status: {
      success: "#3FB950",
      warning: "#D29922",
      error: "#F85149",
      info: "#2F81F7",
    },
    charts: "Sparklines, accent from status palette",
    spacing: [4, 8, 12, 16, 24],
    motion: {
      duration: "120ms",
      easing: "ease-out",
      style: "Instant or quick fade only",
    },
  },
  {
    id: "linear-vercel-dark",
    name: "Linear / Vercel Style",
    mode: "dark",
    personality: "Sleek product-led SaaS — greys, electric accent, sharp UI.",
    colors: {
      primary: "#6366F1",
      secondary: "#22D3EE",
      accent: "#F97316",
      background: "#020617",
      surface: "#050816",
      surfaceMuted: "#0B1020",
      foreground: "#F8FAFC",
      mutedForeground: "#94A3B8",
      border: "#1E293B",
    },
    typography: {
      heading: "Satoshi / Inter",
      body: "Inter",
      h1: "32px / 1.15",
      h2: "22px / 1.2",
      h3: "18px / 1.25",
      bodySize: "14px / 1.55",
      labelSize: "12px / 1.4",
    },
    radius: { sm: "6px", md: "10px", lg: "14px", pill: "999px" },
    shadows: {
      sm: "0 0 0 1px rgba(148, 163, 184, 0.1)",
      md: "0 18px 50px rgba(15, 23, 42, 0.6)",
      lg: "0 24px 64px rgba(15, 23, 42, 0.7)",
    },
    buttons: {
      primary: "Indigo→cyan gradient, white text",
      secondary: "Outline, hover fill surface-alt",
      ghost: "Muted text, bright on hover",
    },
    forms: "Dark surfaces, thin borders, indigo/cyan focus ring",
    cards: "Subtle top gradient bar, vertical stack grouping",
    tables: "Minimal grid, status pills, row bg on hover",
    navigation: "Icon-first sidebar, gradient active item; breadcrumbs in header",
    icons: "Line icons, neon accent on adventure type glyphs",
    status: {
      success: "#22C55E",
      warning: "#FACC15",
      error: "#FB7185",
      info: "#38BDF8",
    },
    charts: "Dark area charts, glow lines, faint grid",
    spacing: [6, 12, 18, 24, 32],
    motion: {
      duration: "160–200ms",
      easing: "cubic-bezier(0.4, 0, 0.2, 1)",
      style: "Nav underline grow, cards fade-up",
    },
  },
  {
    id: "material3-modern",
    name: "Material 3 Modern",
    mode: "light",
    personality: "Google M3 — tonal surfaces, rounded, adaptive color.",
    colors: {
      primary: "#6750A4",
      secondary: "#625B71",
      accent: "#7D5260",
      background: "#FFFBFE",
      surface: "#FEF7FF",
      surfaceMuted: "#E7E0EC",
      foreground: "#1C1B1F",
      mutedForeground: "#49454F",
      border: "#CAC4D0",
    },
    typography: {
      heading: "Roboto Flex",
      body: "Roboto",
      h1: "32px / 1.2 (Display Small)",
      h2: "24px / 1.25 (Headline Small)",
      h3: "20px / 1.3 (Title Large)",
      bodySize: "16px / 1.5 (Body Large)",
      labelSize: "14px / 1.4 (Label Large)",
    },
    radius: { sm: "4px", md: "8px", lg: "12px", pill: "999px" },
    shadows: {
      sm: "Elevation 1",
      md: "Elevation 3",
      lg: "Elevation 5",
    },
    buttons: {
      primary: "Filled tonal buttons per M3 roles",
      secondary: "Outlined + Text variants",
      ghost: "Text button with ripple",
    },
    forms: "Filled text fields, floating labels, strong focus indicator",
    cards: "Elevated + outlined variants, action row at bottom",
    tables: "M3 data table, sticky header, selection states",
    navigation: "Navigation rail (desktop), bar (mobile), FAB for new adventure",
    icons: "Material Symbols Rounded",
    status: {
      success: "#386A20",
      warning: "#7D5700",
      error: "#BA1A1A",
      info: "#00639B",
    },
    charts: "Soft colored columns/lines, M3 grid tokens",
    spacing: [4, 8, 12, 16, 24, 32],
    motion: {
      duration: "200–300ms",
      easing: "M3 standard / emphasized",
      style: "Container transform, shared axis motion",
    },
  },
  {
    id: "enterprise-professional-light",
    name: "Enterprise Professional",
    mode: "light",
    personality: "Notion + Atlassian — serious, configurable, team-ready.",
    colors: {
      primary: "#2563EB",
      secondary: "#0F172A",
      accent: "#0891B2",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceMuted: "#F3F4F6",
      foreground: "#111827",
      mutedForeground: "#6B7280",
      border: "#E5E7EB",
    },
    typography: {
      heading: "Inter / IBM Plex Sans",
      body: "Inter",
      h1: "28px / 1.25",
      h2: "20px / 1.3",
      h3: "16px / 1.35",
      bodySize: "14px / 1.6",
      labelSize: "12px / 1.4",
    },
    radius: { sm: "4px", md: "6px", lg: "8px", pill: "999px" },
    shadows: {
      sm: "0 1px 2px rgba(0, 0, 0, 0.05)",
      md: "0 4px 12px rgba(0, 0, 0, 0.08)",
      lg: "0 12px 28px rgba(0, 0, 0, 0.12)",
    },
    buttons: {
      primary: "Solid blue",
      secondary: "Outlined",
      ghost: "Text + icon tertiary",
    },
    forms: "Label on top, inline descriptions, compact errors",
    cards: "Config panels, split filter + content layouts",
    tables: "Bulk select, filter badges, strong column headers",
    navigation: "Full left nav with sections, team switcher, top search",
    icons: "Lucide + 2-color for adventure/day/moment",
    status: {
      success: "#15803D",
      warning: "#B45309",
      error: "#B91C1C",
      info: "#0369A1",
    },
    charts: "Business bar/line, robust legends",
    spacing: [8, 16, 24, 32],
    motion: {
      duration: "120–150ms",
      easing: "ease-out",
      style: "Dropdowns and modals only",
    },
  },
  {
    id: "luxury-dark",
    name: "Luxury Dark",
    mode: "dark",
    personality: "High-end travel magazine — gold, violet, cinematic.",
    colors: {
      primary: "#EAB308",
      secondary: "#7C3AED",
      accent: "#F97316",
      background: "#05030A",
      surface: "#0B0713",
      surfaceMuted: "#120B21",
      foreground: "#FAF5FF",
      mutedForeground: "#A78BFA",
      border: "#2E1065",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "36px / 1.15",
      h2: "26px / 1.2",
      h3: "20px / 1.25",
      bodySize: "16px / 1.6",
      labelSize: "12px / 1.5 tracking-widest uppercase",
    },
    radius: { sm: "6px", md: "12px", lg: "24px", pill: "999px" },
    shadows: {
      sm: "0 0 24px rgba(234, 179, 8, 0.08)",
      md: "0 8px 32px rgba(124, 58, 237, 0.2)",
      lg: "0 16px 48px rgba(0, 0, 0, 0.6)",
    },
    buttons: {
      primary: "Gold fill, dark text, glow on hover",
      secondary: "Gold outline, transparent bg",
      ghost: "Ivory text, gold underline on hover",
    },
    forms: "Dark fields, gold focus outline, warm grey labels",
    cards: "Full-bleed cover images, gradient overlay, text on top",
    tables: "Dark rows, gold header separators, high contrast",
    navigation: "Minimal top nav; dashboard side rail in deep violet",
    icons: "Thin gold/ivory lines, filled on active only",
    status: {
      success: "#22C55E",
      warning: "#FACC15",
      error: "#FB7185",
      info: "#38BDF8",
    },
    charts: "Gold + violet series, gradient fills to transparent",
    spacing: [8, 16, 24, 40, 64],
    motion: {
      duration: "220–260ms",
      easing: "ease-in-out",
      style: "Cinematic fades, subtle hero parallax",
    },
  },
];

export const lightDesignConcepts = designConcepts.filter((c) => c.mode === "light");
export const darkDesignConcepts = designConcepts.filter((c) => c.mode === "dark");

export function getDesignConceptById(id: string): DesignConcept | undefined {
  return designConcepts.find((c) => c.id === id);
}
