import type { DesignConcept } from "./types";

/** Editorial travel-journal directions — photo-first, magazine feel, not SaaS. */
export const designConcepts: DesignConcept[] = [
  {
    id: "kinfolk-light",
    name: "Kinfolk Journal",
    mode: "light",
    personality: "Soft linen paper, sage and clay, slow travel editorial — Kinfolk meets field notes.",
    colors: {
      primary: "#3D5A4C",
      secondary: "#B8846A",
      accent: "#C17F59",
      background: "#F4F0E8",
      surface: "#FAF8F4",
      surfaceMuted: "#EBE6DC",
      foreground: "#2A2520",
      mutedForeground: "#7A7268",
      border: "#D9D2C6",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "40px / 1.1",
      h2: "28px / 1.15",
      h3: "22px / 1.2",
      bodySize: "17px / 1.65",
      labelSize: "11px / 1.5 tracking-widest uppercase",
    },
    radius: { sm: "4px", md: "8px", lg: "2px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "0 12px 40px rgba(42, 37, 32, 0.06)",
      lg: "0 24px 64px rgba(42, 37, 32, 0.1)",
    },
    buttons: {
      primary: "Clay fill, cream text, minimal radius, no shadow",
      secondary: "Outline sage, transparent bg",
      ghost: "Underline on hover only",
    },
    forms: "Underlined or borderless inputs on paper bg; labels as small caps",
    cards: "Photo-first; text below image; thin border or none; generous vertical rhythm",
    tables: "Avoid — use timeline lists with date column in muted serif",
    navigation: "Minimal top bar, logo serif; no dense sidebar — photo nav tiles",
    icons: "Thin line, muted; never colorful badges",
    status: {
      success: "#5C7A6B",
      warning: "#B8846A",
      error: "#A65D57",
      info: "#3D5A4C",
    },
    charts: "None or single muted sparkline — stats as editorial pull quotes",
    spacing: [8, 16, 24, 40, 64, 96],
    motion: {
      duration: "280ms",
      easing: "ease-out",
      style: "Slow fade; images scale 1→1.02 on hover",
    },
  },
  {
    id: "conde-travel-light",
    name: "Condé Travel",
    mode: "light",
    personality: "High-fashion travel magazine — sharp serif, black ink on cream, one bold accent.",
    colors: {
      primary: "#111111",
      secondary: "#444444",
      accent: "#C41E3A",
      background: "#F7F4EE",
      surface: "#FFFFFF",
      surfaceMuted: "#EFEBE3",
      foreground: "#111111",
      mutedForeground: "#666666",
      border: "#DDDDDD",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "48px / 1.05",
      h2: "32px / 1.1",
      h3: "24px / 1.15",
      bodySize: "16px / 1.6",
      labelSize: "10px / 1.6 tracking-[0.2em] uppercase",
    },
    radius: { sm: "0px", md: "0px", lg: "0px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "none",
      lg: "0 20px 60px rgba(0, 0, 0, 0.08)",
    },
    buttons: {
      primary: "Black fill, white text, square corners",
      secondary: "Red accent outline for key CTA only",
      ghost: "Black text, red underline on hover",
    },
    forms: "Minimal — thin bottom border, black labels, lots of air",
    cards: "Full-bleed image + headline overlay; sharp edges",
    tables: "Editorial data as typographic blocks, not grids",
    navigation: "Centered serif logo; sparse links; hamburger on mobile",
    icons: "Almost none — typography carries navigation",
    status: {
      success: "#2D6A4F",
      warning: "#BC6C25",
      error: "#C41E3A",
      info: "#111111",
    },
    charts: "Large numbers as display type, not chart widgets",
    spacing: [12, 24, 48, 72, 96],
    motion: {
      duration: "200ms",
      easing: "ease-out",
      style: "Hard cuts; no bounce; parallax on hero only",
    },
  },
  {
    id: "golden-hour-light",
    name: "Golden Hour",
    mode: "light",
    personality: "Sunset warmth — amber light on travel photos, emotional and inviting.",
    colors: {
      primary: "#8B5E3C",
      secondary: "#D4A574",
      accent: "#E8923A",
      background: "#FBF6EF",
      surface: "#FFFCF8",
      surfaceMuted: "#F5EBDD",
      foreground: "#3D2E1F",
      mutedForeground: "#8C7B6A",
      border: "#E8D9C8",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "36px / 1.12",
      h2: "26px / 1.18",
      h3: "20px / 1.25",
      bodySize: "17px / 1.65",
      labelSize: "11px / 1.5 uppercase",
    },
    radius: { sm: "6px", md: "10px", lg: "14px", pill: "999px" },
    shadows: {
      sm: "0 2px 12px rgba(139, 94, 60, 0.08)",
      md: "0 16px 48px rgba(139, 94, 60, 0.12)",
      lg: "0 24px 64px rgba(232, 146, 58, 0.15)",
    },
    buttons: {
      primary: "Warm amber gradient, dark text",
      secondary: "Soft cream with amber border",
      ghost: "Amber text link",
    },
    forms: "Warm tinted fields; golden focus ring",
    cards: "Rounded photo cards with warm vignette overlay on images",
    tables: "Timeline with golden date markers",
    navigation: "Light frosted bar over hero photo; warm tint",
    icons: "Warm stroke; sun/map pin accents",
    status: {
      success: "#6B8F71",
      warning: "#E8923A",
      error: "#C45C4A",
      info: "#8B5E3C",
    },
    charts: "Warm area fills, sunset gradient optional on hero only",
    spacing: [8, 16, 24, 40, 56],
    motion: {
      duration: "240ms",
      easing: "ease-in-out",
      style: "Gentle glow fade; warm overlay on scroll",
    },
  },
  {
    id: "gallery-white-light",
    name: "Gallery White",
    mode: "light",
    personality: "Museum catalogue — pure white, photos as art, captions as poetry.",
    colors: {
      primary: "#1A1A1A",
      secondary: "#888888",
      accent: "#555555",
      background: "#FFFFFF",
      surface: "#FFFFFF",
      surfaceMuted: "#F8F8F8",
      foreground: "#1A1A1A",
      mutedForeground: "#999999",
      border: "#EEEEEE",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "44px / 1.08",
      h2: "28px / 1.12",
      h3: "20px / 1.2",
      bodySize: "16px / 1.7",
      labelSize: "10px / 1.6 tracking-widest uppercase",
    },
    radius: { sm: "0px", md: "0px", lg: "0px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
    },
    buttons: {
      primary: "Black text button, bottom border only",
      secondary: "Grey outline, square",
      ghost: "Caption-style link",
    },
    forms: "Invisible until focus — bottom border only",
    cards: "Image with caption below; no card chrome; max whitespace",
    tables: "Never — vertical photo stacks with metadata",
    navigation: "Fixed minimal: logo + one action; rest in footer",
    icons: "Absent or 1px line only",
    status: {
      success: "#4A6741",
      warning: "#8B7355",
      error: "#8B4545",
      info: "#555555",
    },
    charts: "No charts — numbers inline in captions",
    spacing: [16, 32, 48, 80, 120],
    motion: {
      duration: "300ms",
      easing: "ease-out",
      style: "Fade only; no scale or shadow animation",
    },
  },
  {
    id: "postcard-vintage-light",
    name: "Vintage Postcard",
    mode: "light",
    personality: "1950s travel posters — muted teal, coral, nostalgic warmth.",
    colors: {
      primary: "#2E6B7A",
      secondary: "#D4846A",
      accent: "#E8A838",
      background: "#F0EBE3",
      surface: "#FAF6F0",
      surfaceMuted: "#E5DDD2",
      foreground: "#2C2824",
      mutedForeground: "#7A6F65",
      border: "#CFC5B8",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "38px / 1.1",
      h2: "26px / 1.15",
      h3: "20px / 1.22",
      bodySize: "16px / 1.6",
      labelSize: "11px / 1.5 uppercase",
    },
    radius: { sm: "4px", md: "6px", lg: "8px", pill: "999px" },
    shadows: {
      sm: "0 1px 4px rgba(44, 40, 36, 0.1)",
      md: "0 8px 24px rgba(44, 40, 36, 0.12)",
      lg: "0 4px 0 rgba(44, 40, 36, 0.15)",
    },
    buttons: {
      primary: "Teal fill, cream text, slight letter-spacing",
      secondary: "Coral outline",
      ghost: "Teal underline",
    },
    forms: "Postcard-style bordered fields; stamp icon accents",
    cards: "Polaroid tilt optional; white border on photos; hand-stamp labels",
    tables: "Stamp-style date badges in timeline",
    navigation: "Banner-style header with destination name as title",
    icons: "Retro line icons; compass, stamp, pin",
    status: {
      success: "#2E6B7A",
      warning: "#E8A838",
      error: "#C45C4A",
      info: "#D4846A",
    },
    charts: "Poster-style stat blocks with bold numbers",
    spacing: [8, 16, 24, 32, 48],
    motion: {
      duration: "200ms",
      easing: "ease-out",
      style: "Slight card tilt on hover; stamp bounce",
    },
  },
  {
    id: "midnight-cinema-dark",
    name: "Midnight Cinema",
    mode: "dark",
    personality: "Letterbox travel film — dark bars, ivory serif, photos as still frames.",
    colors: {
      primary: "#F5F0E8",
      secondary: "#A89F94",
      accent: "#D4AF6A",
      background: "#0A0A0A",
      surface: "#141414",
      surfaceMuted: "#1E1E1E",
      foreground: "#F5F0E8",
      mutedForeground: "#8A8278",
      border: "#2A2A2A",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "42px / 1.08",
      h2: "28px / 1.12",
      h3: "22px / 1.18",
      bodySize: "16px / 1.65",
      labelSize: "10px / 1.6 tracking-[0.25em] uppercase",
    },
    radius: { sm: "0px", md: "2px", lg: "4px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "0 0 80px rgba(0, 0, 0, 0.8)",
      lg: "inset 0 0 120px rgba(0, 0, 0, 0.5)",
    },
    buttons: {
      primary: "Ivory outline, transparent bg, letterbox feel",
      secondary: "Gold text link",
      ghost: "Muted ivory hover brighten",
    },
    forms: "Dark fields, gold focus line, minimal labels",
    cards: "16:9 photo with black letterbox; title below in serif",
    tables: "Film reel timeline — date as timecode",
    navigation: "Transparent over hero; fades in on scroll",
    icons: "Ivory thin line; gold on active",
    status: {
      success: "#7A9E7E",
      warning: "#D4AF6A",
      error: "#C47A6A",
      info: "#A89F94",
    },
    charts: "No widgets — stats as cinematic intertitles",
    spacing: [8, 16, 32, 48, 80],
    motion: {
      duration: "350ms",
      easing: "ease-in-out",
      style: "Slow fade; letterbox expand on hero load",
    },
  },
  {
    id: "darkroom-dark",
    name: "Darkroom",
    mode: "dark",
    personality: "Photographer's darkroom — charcoal, red safelight accent, film grain.",
    colors: {
      primary: "#E8E4DE",
      secondary: "#9A9590",
      accent: "#C0392B",
      background: "#121110",
      surface: "#1A1918",
      surfaceMuted: "#242220",
      foreground: "#E8E4DE",
      mutedForeground: "#7A7570",
      border: "#33302E",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "36px / 1.1",
      h2: "24px / 1.15",
      h3: "18px / 1.2",
      bodySize: "15px / 1.6",
      labelSize: "10px / 1.5 uppercase",
    },
    radius: { sm: "2px", md: "4px", lg: "6px", pill: "999px" },
    shadows: {
      sm: "0 0 20px rgba(192, 57, 43, 0.06)",
      md: "0 4px 24px rgba(0, 0, 0, 0.5)",
      lg: "0 8px 40px rgba(0, 0, 0, 0.6)",
    },
    buttons: {
      primary: "Red safelight fill on hover; default ivory outline",
      secondary: "Charcoal fill, red border on focus",
      ghost: "Red dot indicator on active nav",
    },
    forms: "Dark inputs; red cursor/focus; monospace for dates",
    cards: "Contact sheet grid; thin white borders between photos",
    tables: "Photo metadata as monospace captions",
    navigation: "Left strip like film edge; red active marker",
    icons: "Camera/aperture line icons; red on record states",
    status: {
      success: "#6B8F71",
      warning: "#C4A035",
      error: "#C0392B",
      info: "#9A9590",
    },
    charts: "Histogram-style bars if needed — monochrome + red",
    spacing: [4, 8, 16, 24, 32],
    motion: {
      duration: "180ms",
      easing: "ease-out",
      style: "Flash fade like shutter; grain overlay static",
    },
  },
  {
    id: "noir-portfolio-dark",
    name: "Noir Portfolio",
    mode: "dark",
    personality: "High-contrast B&W photography portfolio — silver type, dramatic photos.",
    colors: {
      primary: "#E0E0E0",
      secondary: "#888888",
      accent: "#FFFFFF",
      background: "#0D0D0D",
      surface: "#161616",
      surfaceMuted: "#222222",
      foreground: "#F0F0F0",
      mutedForeground: "#707070",
      border: "#333333",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "40px / 1.05",
      h2: "26px / 1.1",
      h3: "20px / 1.15",
      bodySize: "15px / 1.65",
      labelSize: "10px / 1.6 tracking-widest uppercase",
    },
    radius: { sm: "0px", md: "0px", lg: "0px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "0 20px 60px rgba(0, 0, 0, 0.9)",
      lg: "0 0 1px rgba(255, 255, 255, 0.1)",
    },
    buttons: {
      primary: "White outline, fills white on hover with black text",
      secondary: "Grey text only",
      ghost: "Silver underline",
    },
    forms: "White bottom border only; high contrast labels",
    cards: "Full-bleed B&W photo; white title below; zero decoration",
    tables: "Caption blocks, not tables",
    navigation: "Hidden until hover; minimal chrome",
    icons: "White 1px stroke only",
    status: {
      success: "#AAAAAA",
      warning: "#CCCCCC",
      error: "#FFFFFF",
      info: "#888888",
    },
    charts: "None",
    spacing: [16, 32, 48, 64, 96],
    motion: {
      duration: "250ms",
      easing: "ease-out",
      style: "Crossfade between photos; no UI motion",
    },
  },
  {
    id: "velvet-evening-dark",
    name: "Velvet Evening",
    mode: "dark",
    personality: "Boutique hotel journal — deep burgundy, gold serif, intimate luxury.",
    colors: {
      primary: "#D4AF6A",
      secondary: "#9B7B9E",
      accent: "#C45C6A",
      background: "#120A10",
      surface: "#1A1018",
      surfaceMuted: "#241820",
      foreground: "#F5EDE4",
      mutedForeground: "#A89890",
      border: "#3D2838",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "44px / 1.08",
      h2: "28px / 1.12",
      h3: "22px / 1.18",
      bodySize: "16px / 1.65",
      labelSize: "11px / 1.5 tracking-widest uppercase",
    },
    radius: { sm: "4px", md: "8px", lg: "12px", pill: "999px" },
    shadows: {
      sm: "0 0 30px rgba(212, 175, 106, 0.06)",
      md: "0 8px 40px rgba(155, 123, 158, 0.15)",
      lg: "0 16px 60px rgba(0, 0, 0, 0.5)",
    },
    buttons: {
      primary: "Gold fill, dark burgundy text",
      secondary: "Gold outline, transparent",
      ghost: "Gold text with subtle glow on hover",
    },
    forms: "Dark velvet fields; gold focus; elegant labels",
    cards: "Rounded corners; photo with burgundy gradient overlay; gold captions",
    tables: "Elegant list with gold dividers",
    navigation: "Deep sidebar; gold active state; serif logo",
    icons: "Gold thin line; violet secondary",
    status: {
      success: "#7A9E7E",
      warning: "#D4AF6A",
      error: "#C45C6A",
      info: "#9B7B9E",
    },
    charts: "Gold line on dark — minimal",
    spacing: [8, 16, 24, 40, 64],
    motion: {
      duration: "300ms",
      easing: "ease-in-out",
      style: "Soft glow transitions; velvet fade",
    },
  },
  {
    id: "aperture-dark",
    name: "Aperture",
    mode: "dark",
    personality: "Pro photographer portfolio — near-black, warm highlights, content is the photo.",
    colors: {
      primary: "#E8DFD0",
      secondary: "#8B7D6B",
      accent: "#C8956C",
      background: "#0C0B0A",
      surface: "#151310",
      surfaceMuted: "#1E1B18",
      foreground: "#E8DFD0",
      mutedForeground: "#7A7268",
      border: "#2E2A26",
    },
    typography: {
      heading: "Playfair Display",
      body: "Source Sans 3",
      h1: "38px / 1.1",
      h2: "26px / 1.15",
      h3: "20px / 1.2",
      bodySize: "16px / 1.6",
      labelSize: "10px / 1.5 uppercase",
    },
    radius: { sm: "2px", md: "4px", lg: "6px", pill: "999px" },
    shadows: {
      sm: "none",
      md: "0 12px 40px rgba(0, 0, 0, 0.6)",
      lg: "0 0 60px rgba(200, 149, 108, 0.08)",
    },
    buttons: {
      primary: "Warm sand fill, dark text",
      secondary: "Outline sand, transparent",
      ghost: "Sand text link",
    },
    forms: "Minimal dark inputs; warm focus ring",
    cards: "Masonry photo grid; EXIF as meta caption",
    tables: "Gallery index — number + title + date",
    navigation: "Top bar over photos; sand accent on scroll",
    icons: "Aperture, lens, map — warm stroke",
    status: {
      success: "#7A8B6B",
      warning: "#C8956C",
      error: "#A65D57",
      info: "#8B7D6B",
    },
    charts: "Trip stats as large sand numerals beside photos",
    spacing: [8, 16, 24, 32, 48],
    motion: {
      duration: "220ms",
      easing: "ease-out",
      style: "Photo crossfade; UI stays static",
    },
  },
];

export const lightDesignConcepts = designConcepts.filter((c) => c.mode === "light");
export const darkDesignConcepts = designConcepts.filter((c) => c.mode === "dark");

export function getDesignConceptById(id: string): DesignConcept | undefined {
  return designConcepts.find((c) => c.id === id);
}
